apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: toolbox

patches:
- path: deployment.yaml
- path: ingress.yaml

configMapGenerator:
- behavior: replace
  envs:
  - config.properties
  name: app-config

images:
- name: app:latest
  newName: lhr.ocir.io/lrhvckxzwf3l/toolbox
  newTag: ea0e5d8b4f8b4a8683837d2e41d47d095b986fc6
