apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: toolbox

patches:
- path: deployment.yaml
- path: ingress.yaml

configMapGenerator:
- behavior: replace
  envs:
  - config.properties
  name: app-config

images:
- name: app:latest
  newName: lhr.ocir.io/lrhvckxzwf3l/toolbox
  newTag: 970e16dd2ca871a21b503bee647d62ded0e8ab60
